defaultIndent: "  "

verbatimEnvironments:
  example: 1
  code: 1
  chktexignore: 1

verbatimCommands:
  ltx: 1

modifyLineBreaks:
  textWrapOptions:
    columns: 0
    blocksFollow:
      other: |-
        (?x)
        \\\] |
        \\item(?:\h*\[?) |
        \\begin\{lscommand|intro\} |
        \\end\{(?:lscommand|intro|example|code)\}
    blocksBeginWith:
      other: |-
        (?x)
          \\LaTeX |
          \\TeX |
          \\hologo |

          \\normalfont |
          \\textbf |
          \\texttt |

          \\index |

          \\wi |
          \\ei |
          \\eei |
          \\pai |
          \\ci |
          \\demowidth |

          \\\( |
          \\noindent |
          \\hyphenation |
          \\bigskip |
          \\caption |
          \\centerline |
          \\verb |
          \\quad |
          \\emph
